# Generated by Django 4.0.4 on 2022-04-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Headphones', 'Headphones'), ('Game Console', 'Game Console'), ('Phone', 'Phone')], max_length=20, null=True)),
                ('quality', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
