# Generated by Django 4.0.4 on 2022-04-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quality',
            new_name='quantity',
        ),
    ]
